### ISSUE TITLE
Add how to use this library in readme file

### ISSUE THREAD

**Issue by disklosr** [pglazkov/MvvmValidation#1]
I found this interesting library and the readme file only explains how to use it in code, but it doesn't tell how to link the library to a project (via nuget package? via adding source code? etc.)

**Comment by pglazkov** [comment]
Yes, you're right, sorry. I just recently moved the source code from CodePlex and haven't added that info yet. Here is the CodePlex link: http://mvvmvalidation.codeplex.com/. You can download the binaries there. Also you can reference it via NuGet (https://www.nuget.org/packages/MvvmValidation).
