### ISSUE TITLE
Using this library with the JetBrains.Annotations nuget package causes namespace conflicts

### ISSUE THREAD

**Issue by redwolf2** [pglazkov/MvvmValidation#25]
The compiled binary does contain the `JetBrains.Annotations` namespace. This causes a problem on each project that is using the` JetBrains.Annotations` nuget package. You can avoid that by renaming your local `JetBrains.Annotations` namespace to `MvvmValidation.Annotations`.

![grafik](https://user-images.githubusercontent.com/4141621/78363168-96f20900-75bb-11ea-9b3d-ae9f5a853fe1.png)

**Comment by pglazkov** [comment]
Thanks for reporting this issue. Published a fix in version `3.1.1`. Please let me know if it works for you.
