### ISSUE TITLE
Adding nuget package 2.0.2 to project targeting .NET 4.5 will add reference to 4.0 assembly

### ISSUE THREAD

**Issue by mgnslndh** [pglazkov/mvvmvalidation#3]
I added the nuget package 2.0.2 and could not find the `NotifyDataErrorInfoAdapter` that I had seen in the documentation. Looked in the source and there it was. Looked at the assembly reference and noticed that it was to the path `MvvmValidation.2.0.2\lib\net40-client` instead of `MvvmValidation.2.0.2\lib\portable-win8+net45+sl5+wp8`

**Comment by pglazkov** [comment]
Thanks for your feedback! Already working on it. This issue was mentioned here as well: https://github.com/pglazkov/mvvmvalidation/issues/2.

**Comment by pglazkov** [comment]
Fixed. You can try it by installing a pre-release package from NuGet: https://www.nuget.org/packages/MvvmValidation/2.1.0-beta
